/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oodjassignment;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author renee
 */
public class AdminManageRoom extends javax.swing.JFrame {

    /**
     * Creates new form EditRoom1
     */
    public AdminManageRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddRoom = new javax.swing.JButton();
        btnEditRoom = new javax.swing.JButton();
        btnDeleteRoom = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbRoom = new javax.swing.JTable();
        btnBrowse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Manage Room");

        btnAddRoom.setText("Add");
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });

        btnEditRoom.setText("Edit");
        btnEditRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRoomActionPerformed(evt);
            }
        });

        btnDeleteRoom.setText("Delete");
        btnDeleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRoomActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tbRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRoomMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbRoom);

        btnBrowse.setText("Browse...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBrowse)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDeleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBrowse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)
                        .addGap(2, 2, 2)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
         new AdminUpdateRoom().setVisible(true);
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
        new AdminPage().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRoomActionPerformed
        try
        {
            File F = new File("Room.txt");
            BufferedReader br = new BufferedReader(new FileReader(F));
            DefaultTableModel model = (DefaultTableModel)tbRoom.getModel();
            String Line;
            int log = 0;

            int SelectedRowIndex = tbRoom.getSelectedRow();        
            String RoomNo = model.getValueAt(SelectedRowIndex,0).toString();
            String Pax = model.getValueAt(SelectedRowIndex,1).toString();
            String Price = model.getValueAt(SelectedRowIndex,2).toString();
            String Status = model.getValueAt(SelectedRowIndex,3).toString();
            String Applied = model.getValueAt(SelectedRowIndex,4).toString();

            Scanner Sc = new Scanner(F);
            while (Sc.hasNextLine())
            {
                Line = Sc.nextLine();
                String UserLine[] = Line.split(",");
                if(UserLine[0].equals(RoomNo))
                {
                    log = 1;
                }
            }

            if(log==1)
            {
                new AdminEditRoom(RoomNo,Pax,Price,Status,Applied).setVisible(true);
            }
        }
        catch(IOException Ex)
        {
            Ex.printStackTrace();
        }                              
    }//GEN-LAST:event_btnEditRoomActionPerformed

    private void btnDeleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRoomActionPerformed
        DefaultTableModel model = (DefaultTableModel)tbRoom.getModel();
        int SelectedRowIndex = tbRoom.getSelectedRow();
        String RoomNo = model.getValueAt(SelectedRowIndex,0).toString();
        try
        {
            String Line1;
            File F = new File("Room.txt");
            Scanner Sc1 = new Scanner(F);
            boolean log = false;
            while(Sc1.hasNextLine())
            {
                Line1 = Sc1.nextLine();
                String UserLine[] = Line1.split(",");
                if (UserLine[0].equals(RoomNo))
                {
                    log = true;
                }
            }

            if (log == true)
            {
                ArrayList<String> tempArray = new ArrayList<>();
                try
                {
                    try(FileReader fr = new FileReader("Room.txt"))
                    {
                        Scanner Sc2 = new Scanner(fr);
                        String Line2;
                        String[] lineArr;

                        while((Line2 = Sc2.next()) != null)
                        {
                            lineArr = Line2.split(",");
                            if(lineArr[0].equals(RoomNo))
                            {
                                JOptionPane.showMessageDialog(null,"Room Deleted Successfully!","Delete Room",JOptionPane.INFORMATION_MESSAGE);
                            }
                            else
                            {
                                tempArray.add(Line2);
                            }
                        }
                        fr.close();
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace();
                    }
                }
                catch(Exception e)
                {
                      e.printStackTrace();
                }

                try
                {
                    try (PrintWriter pw = new PrintWriter("Room.txt"))
                    {
                        for (String str : tempArray)
                        {
                            pw.println(str);
                        }
                        pw.close();
                    }
                    catch(Exception e)
                    {
                          e.printStackTrace();
                    }
                }
                catch(Exception e)
                {
                      e.printStackTrace();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Invalid Room Number, Please Insert Again!","Failed",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(IOException Ex)
        {
              Ex.printStackTrace();
        }  
        try
        {
            String room = btnDeleteRoom.getText();
            File F = new File("Room.txt");
            BufferedReader br = new BufferedReader(new FileReader(F));
            String firstLine = br.readLine().trim();
            String[] columnName = firstLine.split(",");
            DefaultTableModel model1 = (DefaultTableModel)tbRoom.getModel();
            model1.setColumnIdentifiers(new Object[]{columnName[0],columnName[1],columnName[2],columnName[3],columnName[4]});
            model1.setRowCount(0);

            Object[] tableLines = br.lines().toArray();
            
            for(int i = 0; i < tableLines.length; i++)
            {
                String Line = tableLines[i].toString().trim();
                String[] dataRow = Line.split(",");
                model.addRow(new Object[]{dataRow[0],dataRow[1],dataRow[2],dataRow[3],dataRow[4]});
               
            }
        }
        catch(IOException Ex)
        {
        }                         
    }//GEN-LAST:event_btnDeleteRoomActionPerformed

    private void tbRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRoomMouseClicked
        DefaultTableModel model = (DefaultTableModel)tbRoom.getModel();
        int selectedRowIndex = tbRoom.getSelectedRow();
    }//GEN-LAST:event_tbRoomMouseClicked

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        try
        {
            String room = btnBrowse.getText();
            File F = new File("Room.txt");
            BufferedReader br = new BufferedReader(new FileReader(F));
            String firstLine = br.readLine().trim();
            String[] columnName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)tbRoom.getModel();
            model.setColumnIdentifiers(new Object[]{columnName[0],columnName[1],columnName[2],columnName[3],columnName[4]});
            model.setRowCount(0);

            Object[] tableLines = br.lines().toArray();
            
            for(int i = 0; i < tableLines.length; i++)
            {
                String Line = tableLines[i].toString().trim();
                String[] dataRow = Line.split(",");
                model.addRow(new Object[]{dataRow[0],dataRow[1],dataRow[2],dataRow[3],dataRow[4]});               
            }
        }
        catch(IOException Ex)
        {
              Ex.printStackTrace();
        }                                    
    }//GEN-LAST:event_btnBrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminManageRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnDeleteRoom;
    private javax.swing.JButton btnEditRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbRoom;
    // End of variables declaration//GEN-END:variables
}
